import { useState, useEffect, useCallback } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, AlertCircle, Trash2, RefreshCw } from 'lucide-react';
import {
  RiskScoreCard,
  EvidenceList,
  MissingInfoList,
  QuestionCard,
  DisclaimerBanner,
  FeedbackForm,
} from '@/components';
import { TurnstileChallenge } from '@/components/TurnstileChallenge';
import { api, ApiRequestError } from '@/api';
import { LanguageSwitcher, useI18n } from '@/i18n';
import type { ReportFeedbackRequest, RiskReport } from '@/types';

const reportCopy = {
  'zh-CN': {
    loadFailed: '获取报告失败', confirmDelete: '确定删除该报告及相关数据？删除后无法恢复。',
    deleteRateLimited: '删除请求较频繁，请完成验证后重试。', captchaExpired: '验证已失效，请重新完成验证。',
    deleteFailed: '删除失败', loading: '加载报告中...', errorTitle: '报告获取失败', retry: '重试',
    backHome: '返回首页', notFound: '报告不存在', title: '风险报告', delete: '删除',
    fallback: '当前报告由基础规则检测生成，未使用 AI 深度分析。',
    lowConfidence: '信息不足，建议补充岗位详情或 HR 聊天记录后重新检测。',
    recommendation: '建议', riskTypes: '风险类型', collapseFeedback: '收起反馈', reportFeedback: '报告纠错反馈',
    footer: '本结果基于您提供的信息生成，不构成法律认定或最终就业建议。',
  },
  'en-US': {
    loadFailed: 'Unable to load the report.', confirmDelete: 'Delete this report and its related data? This cannot be undone.',
    deleteRateLimited: 'Too many deletion requests. Complete the verification and try again.', captchaExpired: 'Verification expired. Please complete it again.',
    deleteFailed: 'Unable to delete the report.', loading: 'Loading report...', errorTitle: 'Unable to load report', retry: 'Retry',
    backHome: 'Back to home', notFound: 'Report not found', title: 'Risk report', delete: 'Delete',
    fallback: 'This report was generated by baseline rules without in-depth AI analysis.',
    lowConfidence: 'There is not enough information. Add job details or the HR conversation and run the check again.',
    recommendation: 'Recommendation', riskTypes: 'Risk types', collapseFeedback: 'Hide feedback form', reportFeedback: 'Report an issue',
    footer: 'This result is based on the information you provided and does not constitute a legal determination or final employment advice.',
  },
} as const;

export function ReportPage() {
  const { locale } = useI18n();
  const copy = reportCopy[locale];
  const isEnglish = locale === 'en-US';
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<RiskReport | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [actionError, setActionError] = useState('');
  const [showFeedback, setShowFeedback] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [captchaRequired, setCaptchaRequired] = useState(false);
  const [captchaToken, setCaptchaToken] = useState('');
  const [captchaResetSignal, setCaptchaResetSignal] = useState(0);
  const [deleteCaptchaRequired, setDeleteCaptchaRequired] = useState(false);
  const [deleteCaptchaToken, setDeleteCaptchaToken] = useState('');
  const [deleteCaptchaResetSignal, setDeleteCaptchaResetSignal] = useState(0);

  const loadReport = useCallback(async () => {
    if (!id) return;
    setIsLoading(true);
    setError('');
    try {
      const data = await api.reports.get(id);
      setReport(data);
    } catch (err) {
      const errorMsg = !isEnglish && err instanceof Error ? err.message : copy.loadFailed;
      setError(errorMsg);
    } finally {
      setIsLoading(false);
    }
  }, [copy.loadFailed, id, isEnglish]);

  useEffect(() => {
    loadReport();
  }, [loadReport]);

  useEffect(() => {
    if (!report || window.location.hash !== '#follow-up-questions') return;
    window.requestAnimationFrame(() => {
      document.getElementById('follow-up-questions')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
  }, [report]);

  const handleDelete = useCallback(async () => {
    if (!id || !window.confirm(copy.confirmDelete)) {
      return;
    }
    setIsDeleting(true);
    setActionError('');
    try {
      await api.reports.delete(id, deleteCaptchaToken || undefined);
      if (localStorage.getItem('latest_report_id') === id) localStorage.removeItem('latest_report_id');
      window.location.href = '/';
    } catch (err) {
      if (err instanceof ApiRequestError && err.code === 'CAPTCHA_REQUIRED') {
        setDeleteCaptchaRequired(true);
        setActionError(copy.deleteRateLimited);
      } else if (err instanceof ApiRequestError && err.code === 'CAPTCHA_FAILED') {
        setDeleteCaptchaRequired(true);
        setDeleteCaptchaToken('');
        setDeleteCaptchaResetSignal(value => value + 1);
        setActionError(copy.captchaExpired);
      } else {
        setActionError(!isEnglish && err instanceof Error ? err.message : copy.deleteFailed);
      }
    } finally {
      setIsDeleting(false);
    }
  }, [copy.captchaExpired, copy.confirmDelete, copy.deleteFailed, copy.deleteRateLimited, deleteCaptchaToken, id, isEnglish]);

  const handleFeedback = useCallback(async (data: { type: string; content: string }) => {
    if (!id) return;
    try {
      await api.feedbacks.report({
        report_id: id,
        feedback_type: data.type as ReportFeedbackRequest['feedback_type'],
        content: data.content,
        captcha_token: captchaToken || undefined,
      });
    } catch (err) {
      if (err instanceof ApiRequestError && err.code === 'CAPTCHA_REQUIRED') {
        setCaptchaRequired(true);
      } else if (err instanceof ApiRequestError && err.code === 'CAPTCHA_FAILED') {
        setCaptchaRequired(true);
        setCaptchaToken('');
        setCaptchaResetSignal(value => value + 1);
      }
      throw err;
    }
  }, [captchaToken, id]);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-primary-200 border-t-primary-500 rounded-full animate-spin mx-auto mb-4" />
          <p className="text-gray-500">{copy.loading}</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4">
        <div className="text-center max-w-md">
          <AlertCircle className="w-16 h-16 text-danger-500 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-800 mb-2">{copy.errorTitle}</h2>
          <p className="text-gray-500 mb-6">{error}</p>
          <div className="flex gap-3 justify-center">
            <button
              onClick={loadReport}
              className="px-4 py-2 rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-100 flex items-center gap-2"
            >
              <RefreshCw className="w-4 h-4" />
              {copy.retry}
            </button>
            <Link
              to="/"
              className="px-4 py-2 rounded-lg gradient-primary text-white hover:opacity-90"
            >
              {copy.backHome}
            </Link>
          </div>
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4">
        <div className="text-center">
          <AlertCircle className="w-16 h-16 text-gray-400 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-800 mb-2">{copy.notFound}</h2>
          <Link
            to="/"
            className="inline-block mt-4 px-4 py-2 rounded-lg gradient-primary text-white"
          >
            {copy.backHome}
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white/80 backdrop-blur-sm border-b border-gray-100 sticky top-0 z-50">
        <div className="max-w-2xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link
            to="/"
            className="flex items-center gap-2 text-gray-700 hover:text-primary-600"
          >
            <ArrowLeft className="w-5 h-5" />
            <span className="hidden text-sm font-medium sm:inline">{copy.backHome}</span>
          </Link>
          <span className="text-base font-bold text-gray-800 sm:text-lg">{copy.title}</span>
          <div className="flex items-center gap-2">
            <LanguageSwitcher />
            <button
              onClick={handleDelete}
              disabled={isDeleting || (deleteCaptchaRequired && !deleteCaptchaToken)}
              title={copy.delete}
              aria-label={copy.delete}
              className="rounded-md p-2 text-danger-600 hover:bg-danger-50 hover:text-danger-700 disabled:opacity-50"
            >
              {isDeleting ? (
                <RefreshCw className="w-4 h-4 animate-spin" />
              ) : (
                <Trash2 className="w-4 h-4" />
              )}
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-4 py-6 space-y-4">
        {actionError && (
          <div className="text-sm text-danger-600 bg-danger-50 rounded-lg p-3">
            {actionError}
          </div>
        )}
        {deleteCaptchaRequired && (
          <div className="rounded-xl bg-white border border-gray-100 p-4">
            <TurnstileChallenge
              onVerify={setDeleteCaptchaToken}
              resetSignal={deleteCaptchaResetSignal}
            />
          </div>
        )}
        {report.analysis_source === 'fallback' && (
          <div className="rounded-xl bg-warning-50 border border-warning-200 p-4">
            <p className="text-sm text-warning-700">
              <AlertCircle className="w-4 h-4 inline mr-1" />
              {copy.fallback}
            </p>
          </div>
        )}
        {report.confidence === '低' && (
          <div className="rounded-xl bg-warning-50 border border-warning-200 p-4">
            <p className="text-sm text-warning-700">
              <AlertCircle className="w-4 h-4 inline mr-1" />
              {copy.lowConfidence}
            </p>
          </div>
        )}

        <RiskScoreCard
          score={report.overall_score}
          riskLevel={report.risk_level}
          confidence={report.confidence}
          predictedRole={report.predicted_role}
        />

        {report.recommendation && (
          <div className="rounded-xl bg-white border border-gray-100 p-5">
            <h3 className="text-sm font-semibold text-gray-700 mb-2">{copy.recommendation}</h3>
            <p className="text-sm text-gray-600">{report.recommendation}</p>
          </div>
        )}

        {report.risk_types.length > 0 && (
          <div className="rounded-xl bg-white border border-gray-100 p-5">
            <h3 className="text-sm font-semibold text-gray-700 mb-3">{copy.riskTypes}</h3>
            <div className="flex flex-wrap gap-2">
              {report.risk_types.map((type, index) => (
                <span
                  key={index}
                  className="px-3 py-1 rounded-full text-xs font-medium bg-danger-100 text-danger-700"
                >
                  {type}
                </span>
              ))}
            </div>
          </div>
        )}

        <EvidenceList evidence={report.evidence} />

        <MissingInfoList missingInfo={report.missing_info} />

        <div id="follow-up-questions" className="scroll-mt-24">
          <QuestionCard questions={report.questions} />
        </div>

        <DisclaimerBanner />

        <div className="rounded-xl bg-white border border-gray-100 p-5">
          <button
            onClick={() => setShowFeedback(!showFeedback)}
            className="text-sm font-semibold text-primary-600 hover:text-primary-700 flex items-center gap-2"
          >
            {showFeedback ? copy.collapseFeedback : copy.reportFeedback}
          </button>
          {showFeedback && (
            <div className="mt-4 pt-4 border-t border-gray-200">
              {captchaRequired && (
                <div className="mb-4">
                  <TurnstileChallenge
                    onVerify={setCaptchaToken}
                    resetSignal={captchaResetSignal}
                  />
                </div>
              )}
              <FeedbackForm
                onSubmit={handleFeedback}
                disabled={captchaRequired && !captchaToken}
              />
            </div>
          )}
        </div>
      </main>

      <footer className="mt-8 py-6 border-t border-gray-100 bg-white">
        <div className="max-w-2xl mx-auto px-4 text-center">
          <p className="text-xs text-gray-400">
            {copy.footer}
          </p>
        </div>
      </footer>
    </div>
  );
}
